services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: db_uscs_ic
      MYSQL_ROOT_PASSWORD: 1404
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d

  api:
    build: .
    container_name: fastapi_app
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8001:8001"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: 1404
      DB_NAME: db_uscs_ic
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - db
      - rabbitmq

  worker_notificacao:
    build: .
    container_name: notificacao_worker
    command: python -m app.adapters.workers.notificacao_consumer
    volumes:
      - .:/app
    working_dir: /app
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: 1404
      DB_NAME: db_uscs_ic
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - rabbitmq
      - db

volumes:
  db_data: